### ISSUE TITLE
Access via HTTP

### ISSUE THREAD

**Issue by cutls** [DavidLibeau/search-mastodon-tools#6]
We can also access this service via HTTP without redirecting.
I know HTTPS access has been already available.

When search form is used via HTTP, some browsers show alert like "Not Secure".

**Comment by DavidLibeau** [comment]
So you suggest to have strict HTPPS with redirection?
(Note that, for privacy purpose, the website does not transmit anything to the server when you search something.)

**Comment by cutls** [comment]
Yes, redirecting is required, although data of search form is not sent to server.
Chrome 62 and above show an alert if there is a form on HTTP site, even without sending data.
